### ISSUE TITLE
请问，Go编译出来的DLL，Go分配的内存还能被GC掉吗？

### ISSUE THREAD

**Issue by orangetangerine** [Baozisoftware/go-dll#1]
RT
比如我用golang编译得到一个DLL，代码里面各种new。
然后C++调用这个DLL。
go代码分配的内存能被释放吗？
换句话应该就是Go的Runtime在里面吗？
谢谢

**Comment by Baozisoftware** [comment]
go编写的dll内存部分是由go运行时管理的.
