### ISSUE TITLE
关于返回goslice

### ISSUE THREAD

**Issue by xiongyejun** [Baozisoftware/go-dll#3]
按你这个方法可以实现go制作dll，我使用vba比较多，希望能用go制作vba调用的dll，也碰到了返回Slice直接崩溃的情况，在网上找了些资料，问题得到了解决：
Golang 是一个有垃圾回收的语言，所以任何 Golang 的对象指针不应该直接传递到外面，更好的方法可能是：使用cgo申请内存，将内存数据复制出来，返回申请内存的指针，同时也要导出1个Free函数，外部调用记得最后free。

//export ReurnSlice
func ReurnSlice() (ptr unsafe.Pointer, iLen, iCap int) {
	s := make([]int, 0, 10)
	s = append(s, 23)
	s = append(s, 231)
	s = append(s, 234)

	ptr = C.malloc(C.uint(4 * cap(s)))
	C.memcpy(ptr, unsafe.Pointer(&s[0]), C.uint(4*cap(s)))
	return ptr, len(s), cap(s)
}

//export Free
func Free(p unsafe.Pointer) {
	C.free(p)
}

还有个问题想请教：
我想做个使用SQLite的dll，但是编译的dll读取的时候就直接出错，能否帮忙测试研究研究。

**Comment by Baozisoftware** [comment]
你的解决问题的思路不错,就是手动释放有点麻烦.
另外关于你的sqlite的问题,我也没实际操作过,也许你可以用打log的方式调试一下?
